### PR TITLE
Fallback to access_token if id_token is not present

### LINKED ISSUE #39: Current master branch fails with `token_id` key not found
It seems when installing from master and running through the example, there is an issue with some 2nd+ level dependency that may have been updated, resulting in the basic auth workfow (eg the one in the readme) no longer working.

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #39

### CODE REVIEW

**Review by agrski — APPROVED** [review]
LGTM

I've checked out the PR and run a minimal example with `config.auth_method = "client_credentials"` to verify it.  Client creds doesn't have an `id_token` for me when running with Keycloak 10.0.2, but this PR successfully returns the access token for me.

**Comment by adriangonz** [comment]
That's really interesting @agrski. I remember that the code, as it was, used to work on trial setups with Keycloak. Do you think that something may have changed on the latest version of Keycloak so that the `id_token` is not there anymore?

**Comment by agrski** [comment]
> That's really interesting @agrski. I remember that the code, as it was, used to work on trial setups with Keycloak. Do you think that something may have changed on the latest version of Keycloak so that the `id_token` is not there anymore?

I remember testing client creds for the 1.4.0 release and it was happy then.  At that point I would have been using Keycloak 8.3.0, so quite possible it's become more conservative in its behaviour since between those versions.

**Comment by SachinVarghese** [comment]
Nice one @adriangonz ! 

@agrski I'm not sure what the default scopes are but you need to pass the `openid` scope to get id tokens.

**Comment by agrski** [comment]
> @agrski I'm not sure what the default scopes are but you need to pass the `openid` scope to get id tokens.

The [default scopes](https://github.com/SeldonIO/seldon-deploy-sdk/blob/50b64f290893feead6dcf18f99fcb35f6f880774/templates/python/configuration.mustache#L70) do include `openid`, so it seems like providers being strict about their handling of the different auth methods.
Good reminder though!  I'd forgotten about that :sweat_smile:

**Pull request merged**
